##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-desktop
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgtk-3-dev
    - libgtk-3-doc
    - libstartup-notification0-dev
    - libtool
    - libx11-dev
    - libxml2-dev
    - libxrandr-dev
    - meson

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - mkdir html-report
  - cppcheck $ARGS_CPPCHECK . 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}

  - ./make-scanbuild '--prefix=/usr --enable-gtk-doc --enable-compile-warnings=maximum'

  - ./after-build

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     if [ -f "gen-index" ]; then ./gen-index -l 20; fi
  - fi

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: cafe-desktop-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.cafe-desktop.org/release
