##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-desktop
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgtk-3-dev
    - libgtk-3-doc
    - libstartup-notification0-dev
    - libtool
    - libx11-dev
    - libxml2-dev
    - libxrandr-dev
    - meson

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - export TITLESCANBUILD="${REPO_NAME} (clang-tools `dpkg -s clang-tools|grep -i version|cut -d " " -f 2`) - scan-build results"
  - mkdir html-report
  - cppcheck $ARGS_CPPCHECK . 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --prefix=/usr --enable-gtk-doc
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --html-title="$TITLESCANBUILD" --keep-cc -o html-report make -j $CPU_COUNT 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - else
  -     scan-build $CHECKERS --html-title="$TITLESCANBUILD" --keep-cc -o html-report make 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - fi
  - make check 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - echo Warnings detected in the logs `cat ./html-report/output_${TRAVIS_COMMIT} | grep -i warning | wc -l` 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - make install

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     make distcheck
  -     if [ -f "gen-index" ]; then ./gen-index -l 20; fi
  - fi

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: cafe-desktop-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.cafe-desktop.org/release
