##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:

before_scripts:
  - ./debrepo-install

build_scripts:
  - ./build-debs https://github.com/cafe-desktop/debian-packages devel cafe-desktop

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/cafe-desktop/cafe-desktop/raw/master/icons/16x16/apps/cafe-desktop.png; fi
  - fi
