##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/cafe-desktop
    - autoconf-archive
    - automake
    - clang
    - gcc
    - git
    - gtk-doc
    - gobject-introspection
    - gtk3
    - intltool
    - iso-codes
    - libtool
    - meson
    - make
    - pkgconf
    - startup-notification
    - which

  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-desktop
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgtk-3-dev
    - libgtk-3-doc
    - libstartup-notification0-dev
    - libtool
    - libx11-dev
    - libxml2-dev
    - libxrandr-dev
    - meson

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/cafe-desktop.git
    - autoconf-archive
    - cairo-gobject-devel
    - clang-analyzer
    - clang
    - dconf-devel
    - desktop-file-utils
    - gcc
    - gettext-devel
    - git
    - gtk-doc
    - gobject-introspection-devel
    - gtk3-devel
    - iso-codes-devel
    - itstool
    - libtool
    - make
    - meson
    - redhat-rpm-config
    - startup-notification-devel
    - which

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdconf-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgtk-3-dev
    - libgtk-3-doc
    - libstartup-notification0-dev
    - libtool
    - libx11-dev
    - libxml2-dev
    - libxrandr-dev
    - meson

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  # Install cafe-common from master branch
  - if [ ! -e cafe-common-master ]; then
  -     cd ${START_DIR}
  -     git clone --depth 1  https://github.com/cafe-desktop/cafe-common.git -b master cafe-common-master
  -     cd cafe-common-master
  -     ./autogen.sh
  -     if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -         ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  -     else
  -         ./configure --prefix=/usr
  -     fi
  -     make
  -     make install
  - fi

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --prefix=/usr --enable-gtk-doc
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     make distcheck
  - fi

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: cafe-desktop-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.cafe-desktop.org/release
